Todo/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('Todo_app/', include('Todo_app.urls')),
]

Todo_app/urls.py
from django.urls import path
from . import views

app_name = 'Todo_app'

urlpatterns = [
    path('vonly/', views.TodoVueOnlyTV.as_view(), name='vonly'),
    path('create/', views.TodoCV.as_view(), name='create'),
    path('list/', views.TodoLV.as_view(), name='list'),
    path('<int:pk>/delete/', views.TodoDelV.as_view(), name='delete'), # <int:pk> path converter는 숫자를 인자로 받아서 view에 넘겨줍니다. 
    path('mixin/', views.TodoMOMCV.as_view(), name='mixin'),
    path('<int:pk>/delete2/', views.TodoDelv2.as_view(), name='delete2')
]

Todo_app/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self) :
        return self.todo

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None) :
        # 오버라이딩 질문
        if not self.name:
            self.name = '홍길동'
        super().save()

Todo/views.py
from django.views.generic import TemplateView

class HomeView(TemplateView):
    template_name = "home.html"

Todo_app/views.py
from django.views.generic import TemplateView, CreateView, ListView, DeleteView
from django.views.generic.list import MultipleObjectMixin
from Todo_app.models import Todo
from django.urls import reverse_lazy

class TodoMOMCV(MultipleObjectMixin, CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'Todo_app/todo_mixin.html'
    success_url = reverse_lazy('Todo_app:mixin') 

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset() 
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()
        return super().post(request, *args, **kwargs)

class TodoVueOnlyTV(TemplateView) :
    template_name = 'Todo_app/todo_vue_only.html'

class TodoCV(CreateView) :
    model = Todo
    fields = '__all__'
    template_name = 'Todo_app/todo_form.html'
    success_url = reverse_lazy('Todo_app:list')

class TodoLV(ListView) :
    model = Todo # 리스트 뷰를 사용함으로서 Todo라는 데이터베이스의 자료를 자동으로 템플릿에게 넘겨주게 됩니다. 
    template_name = 'Todo_app/todo_list.html'

class TodoDelV(DeleteView) :
    model = Todo
    template_name = 'Todo_app/todo_confirm_delete.html'
    success_url = reverse_lazy('Todo_app:list')

class TodoDelv2(DeleteView) :
    model = Todo
    # template_name = 'Todo_app/todo_confirm_delete.html'
    success_url = reverse_lazy('Todo_app:mixin')

    def get(self, request, *args, **kwargs) :
        return self.delete(request, *args, **kwargs)

Todo_app/templates/Todo_app/todo_confirm_delete.html
{% extends 'base.html' %}
    
{% block title %} todo_confirm_delete.html {% endblock  %}
{% block extra-style %}

    <style>
        .inputBox {
            background-color: white;
            display: flex;
            border-radius: 30px;
            justify-content: center;
            margin:auto;
            width: 80%;
            height: 50%;
        }

        .inputBox__name {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 40%;
            margin-left: 20px;
        }

        .inputBox__todo {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 60%;
            margin-left: 10px;
        }

        .inputBox__add {
            border-style:none;
            border-bottom:1px solid #ddd;
            margin-right : 20px;
            width: 200px;
        }

        .todoList {
            background-color: white;
        }

        .removeBtn {
            margin-left: auto;
            font-size: 20px;;
        }


        body {
            padding-top: 70px;
            background-color: skyblue;
            text-align: center;
        };
    </style>
{% endblock  %}
{% block content %}
    <div>
        <h2>TODO Delete</h2>
        <p>Are you sure to delete? {{ todo }}</p>
    </div>

    <form action="." method='post'> {% csrf_token %}
        <button type='submit' class="btn btn-danger btn-sm">
            Confirm
        </button>
    </form>
{% endblock  %}

Todo_app/templates/Todo_app/todo_form.html
{% extends 'base.html' %}

    {% block title %} todo_form.html {% endblock %}
    {% block extra-style %}
    
    <style>
        .inputBox {
            background-color: white;
            display: flex;
            border-radius: 30px;
            justify-content: center;
            margin:auto;
            width: 80%;
            height: 50%;
        }

        .inputBox__name {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 40%;
            margin-left: 20px;
        }

        .inputBox__todo {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 60%;
            margin-left: 10px;
        }

        .inputBox__add {
            border-style:none;
            border-bottom:1px solid #ddd;
            margin-right : 20px;
            width: 200px;
        }

        .todoList {
            background-color: white;
        }

        .removeBtn {
            margin-left: auto;
            font-size: 20px;;
        }


        body {
            padding-top: 70px;
            background-color: skyblue;
            text-align: center;
        };
</style>
{% endblock  %}
{% block content %}
    <div id='app'>
        <h1>My Todo App!</h1>

        <h5>JSH - 개발 시작 04.03 @BEM 방식 반드시 준수@</h5>
        <br>

        <form class="inputBox" method = 'post', action="."> {% csrf_token %}
            <div class="inputBox__name">
                <input type="text" placeholder ="name..." name='name'>  <!--아래있는 변수와 input tag를 바인딩 해줍니다 이런 방식의 바인딩을 한다면 아래 Vue 파트와 양방향으로 정보를 주고 받을 수 있습니다.-->
            </div>
            <div class="inputBox__todo">
                <input type="text" required placeholder="Enter What you want!" name="todo" > <!--name은 장고의 model의 컬럼명과 동일해야합니다. -->
            </div> 
            <button type='submit' class="btn btn-info btn-sm">Add</button>
        </form>
    
    </div>
{% endblock  %}

{% block footer %}{% endblock  %}

Todo_app/templates/Todo_app/todo_list.html
{% extends 'base.html' %}

{% block title %} todo_list.html {% endblock %} 
{% block extra-style %}
    
    <style>
        .inputBox {
            background-color: white;
            display: flex;
            border-radius: 30px;
            justify-content: center;
            margin:auto;
            width: 80%;
            height: 50%;
        }

        .inputBox__name {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 40%;
            margin-left: 20px;
        }

        .inputBox__todo {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 60%;
            margin-left: 10px;
        }

        .inputBox__add {
            border-style:none;
            border-bottom:1px solid #ddd;
            margin-right : 20px;
            width: 200px;
        }

        .todoList {
            background-color: white;
        }

        .removeBtn {
            margin-left: auto;
            font-size: 20px;;
        }


        body {
            padding-top: 70px;
            background-color: skyblue;
            text-align: center;
        };
    </style>
    {% endblock  %}

{% block content %}

    <div id='app'>
        <h1>My Todo App!</h1>

        <h5>JSH - 개발 시작 04.03 @BEM 방식 반드시 준수@</h5>
        <br>

        
            <ul class="todoList">
                {% for todo in object_list %}
                <li>
                    <span>{{ todo.name }}:: {{ todo.todo }}</span>
                    <span class="removeBtn"><a href="{% url 'Todo_app:delete' todo.id %}">&#x00D7</a></span>
                </li>
                {% endfor %}
            </ul>
    </div>
{% endblock  %}

Todo_app/templates/Todo_app/todo_mixin.html
{% extends 'base.html' %}

{% block title %} todo_form_list.html {% endblock %}
{% block extra-style %}
    
    <style>
        .inputBox {
            background-color: white;
            display: flex;
            border-radius: 30px;
            justify-content: center;
            margin:auto;
            width: 80%;
            height: 50%;
        }

        .inputBox__name {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 40%;
            margin-left: 20px;
        }

        .inputBox__todo {
            border-style:none;
            border-bottom:1px solid #ddd;
            width: 60%;
            margin-left: 10px;
        }

        .inputBox__add {
            border-style:none;
            border-bottom:1px solid #ddd;
            margin-right : 20px;
            width: 200px;
        }

        .todoList {
            background-color: white;
        }

        .removeBtn {
            margin-left: auto;
            font-size: 20px;;
        }

        .removeBtn:hover {
            color: red;
        }

        .modal-footer a {
            color: white;
        }

        body {
            padding-top: 70px;
            background-color: skyblue;
            text-align: center;
        };
</style>
{% endblock  %}
{% block content %}
<div id='app'>
    <h1>My Todo App!</h1>

    <h5>JSH - 개발 시작 04.03 @BEM 방식 반드시 준수@ dkwkdkwd</h5>
    <br>

    <form class="inputBox" method = 'post', action="."> {% csrf_token %}
        <div class="inputBox__name">
            <input type="text" placeholder ="name..." name='name'>  <!--아래있는 변수와 input tag를 바인딩 해줍니다 이런 방식의 바인딩을 한다면 아래 Vue 파트와 양방향으로 정보를 주고 받을 수 있습니다.-->
        </div>
        <div class="inputBox__todo">
            <input type="text" required placeholder="Enter What you want!" name="todo" > <!--name은 장고의 model의 컬럼명과 동일해야합니다. -->
        </div> 
        <button type='submit' class="btn btn-info btn-sm">Add</button>
    </form>
    <ul class="todoList">
        {% for todo in object_list %}
            <li>
                <span>{{ todo.name }}:: {{ todo.todo }}</span>
                <span class="removeBtn" data-toggle="modal" data-target = #myModal 
                    data-id = "{{todo.id}}" data-todo = "{{todo.todo}}" data-name = "{{todo.name}}">&#x00D7</a></span>
            </li>
        {% endfor %}
    </ul>
     <!-- Modal -->
    <div class="modal" id="myModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Are you sure to delete ?</h5>
                </div>
                <div class="modal-body">
                    body-text
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-danger btn-sm">
                        <a href="">Delete</a></button>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock  %}

{% block extra-script %}
<script>
$('#myModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var id = button.data('id')
    var name = button.data('name')
    var todo = button.data('todo')

    var modal = $(this)
    modal.find('.modal-body').text(name + '::: ' + todo)
    modal.find('.modal-footer a').attr('href', '/todo/' + id + '/delete2/')
})
</script>
{% endblock %}

Todo_app/templates/Todo_app/todo_vue_only.html
{% extends 'base.html' %}

{% block title %}todo_vue_only.html{% endblock %}
{% block extra-style %}
<style>
.inputBox {
background-color: white;
display: flex;
border-radius: 30px;
justify-content: center;
margin:auto;
width: 80%;
height: 50%;
}

.inputBox__name {
border-style:none;
border-bottom:1px solid #ddd;
width: 40%;
margin-left: 20px;
}

.inputBox__todo {
border-style:none;
border-bottom:1px solid #ddd;
width: 60%;
margin-left: 10px;
}

.inputBox__add {
border-style:none;
border-bottom:1px solid #ddd;
margin-right : 20px;
width: 200px;
}

.todoList {
background-color: white;
}

.removeBtn {
margin-left: auto;
font-size: 20px;;
}


body {
padding-top: 70px;
background-color: skyblue;
text-align: center;
}
</style>
{% endblock %}    
    
{% block content %}
    <div id=app>
        <h1>My Todo App!</h1>

        <h5>JSH - 개발 시작 04.03 @BEM 방식 반드시 준수@</h5>
        <br>

        <div class="inputBox">
            <div class="inputBox__name">
                <input type="text" required placeholder ="name..." v-model='name'>  <!--아래있는 변수와 input tag를 바인딩 해줍니다 이런 방식의 바인딩을 한다면 아래 Vue 파트와 양방향으로 정보를 주고 받을 수 있습니다.-->
            </div>
            <div class="inputBox__todo">
                <input type="text" required placeholder="Enter What you want!" v-model="newTodoItem" v-on:keyup.enter="add_todo">
            </div> 
            <button v-on:click= "add_todo" >
                Add
            </button>
        </div>
        
            <ul class="todoList">
                <li v-for = "(todo, index) in todoItems">
                    <span>{ todo.name }:: { todo.item }</span>
                    <span v-on:click="remove_todo(index)" class="removeBtn">&#x00D7</span>
                </li>
            </ul>
    </div>
{% endblock %}

{% block extra-script %}

    <script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
    <script>
        var vm = new Vue({
            delimiters: ['{', '}'],
            el: '#app',
            data: {
                name : '',
                newTodoItem: '',
                todoItems:[
                    {name: '정승화', item: 'Django와 Vue를 사용한 Todo 프로그램 제작'},
                    {name: '장동건', item: '굉장히 부담스럽네요'},
                    {name: '원빈', item: '해커톤은 처음이라서요 잘 부탁드려요'}       
                ]
            },
            methods: {
                add_todo: function() {
                    console.log("할 일을 추가합니다...");
                    if(this.name == '') this.name = "홍길동";
                    if(this.newTodoItem== '') return;

                    this.todoItems.push({name: this.name, item: this.newTodoItem});
                    this.name ='';
                    this.newTodoItem = '';
                },

                remove_todo: function(index) {
                    console.log("할 일을 삭제 합니다...");
                    this.todoItems.splice(index, 1)
                }
            },            
        })
    </script>
{% endblock  %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
    <title>{% block title %}home.html{% endblock %}</title>

    {% block extra-style %} {% endblock %}
</head>

<body>
    
    <nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">

        <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>
    
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
            <span class="navbar-toggler-icon"></span>
        </button>
    
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'Todo_app:vonly' %}">VueOnly</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'Todo_app:create' %}">DjangoOnly</a></li>
                <li class="nav-item mx-1 btn btn-primary">
                    <a class="nav-link text-white" href="{% url 'Todo_app:mixin' %}">DjangoMixin</a></li>
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                        <div class="dropdown-divider"></div>
                    </div>
                </li>
            </ul>
    
            <form class="form-inline my-2">
                <input class="form-control mr-sm-2" type="search" placeholder="Search">
            </form>
    
            <ul class="navbar-nav ml-5 mr-5">
                <li class="nav-item dropdown mx-1 btn btn-primary">
                    <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                        <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                        <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                    </div>
                </li>
            </ul>
    
        </div>
    </nav>

    <div class="container">
        {% block content %} {% endblock %}
    </div>

    {% block footer %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

    {% block extra-script %}{% endblock %}
</body>

</html>

templates/home.html
{% extends 'base.html' %}


{% block title %} home.html {% endblock  %}
{% block extra-style %}
<style>
.wrapper{
    display: flex;
    justify-content: center;
    align-items: center;
    min-height: 100vh;
}
</style>
{% endblock  %}
{% block content %}    
    <div class='wrapper'>
        <span data-toggle="tooltip" data-placement="top" title="Tooltip on top">Tooltip on top</span>
    </div>
{% endblock  %}

{% block footer %}
{% endblock %}

{% block extra-script %}
<script>
$(function () {
	$('[data-toggle="tooltip"]').tooltip();
});
</script>
{% endblock %}